language: bash
services: docker

env:
  - VERSION=2.4
  - VERSION=2.4 VARIANT=alpine
  - VERSION=2.2
  - VERSION=2.2 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="httpd:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
